#!/bin/bash

set -e

mysql -u "${POSTGRES_USER}" <<-EOSQL
CREATE USER ${DB_USERNAME} IDENTIFIED BY '${DB_PASSWORD}';
CREATE DATABASE ${DB_DATABASE};
GRANT ALL PRIVILEGES ON DATABASE ${DB_DATABASE}.* TO ${DB_USERNAME};
EOSQL
